project:
  type: book
  output-dir: docs

book:
  title: "R Package Essentials"
  author: "Nicholas Tierney"
  description: |
     I first learnt to write an R package from Hilary Parker's famous blog post, ["Writing an R package from scratch"](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/). Then I consulted [Hadley Wickham's "R packages" book (1st edition)](https://r-pkgs.org/). I consider the "R packages" book (now in its second edition, by Hadley Wickham and Jenny Bryan), to be the authority on best practices for package development, alongside the rOpenSci guide, ["rOpenSci Packages: Development, Maintenance, and Peer Review"](https://devguide.ropensci.org/index.html), by Salmon et al. These are excellent pieces of reference test, however I think there is a need for a resource that sits somewhere between a blog post on making an R package, and resource. I want something that contains __just enough__ information to get you started on the right path to making an R package. This is what that book represents to me. Along the way I'll include breadcrumbs to other resources to look into when you want to learn more.
  site-url: https://rpkgess.njtierney.com
  repo-url: https://github.com/njtierney/rpkgess
  repo-branch: main
  repo-actions: [edit, issue]
  # sharing: [twitter]
  date: "2025-04-08"
  page-footer: "Copyright 2025, Nicholas Tierney"
  page-navigation: true
  search: true
  chapters:
    - "index.qmd"
    - "license.qmd"
    - "philosophy.qmd"
    - "installation.qmd"
    - "rstudio.qmd"
    - "workflow.qmd"
    - "why-functions.qmd"
    - "motivation.qmd"
    - "create-the-pkg.qmd"
    - "how-to-use-extra-pkgs.qmd"
    - "add-documentation.qmd"
    - "add-data.qmd" #
    - "using-checks.qmd"
    - "add-vignette.qmd"
    - "add-readme.qmd"
    - "push-to-github.qmd"
    - "add-tests.qmd"
    - "add-website.qmd"
    - "add-ci.qmd"
    - "publish.qmd" # on R universe
    - "next-steps.qmd" # R-Packages book, rOpenSci, AI tools
    - "references.qmd"
    - "acknowledgements.qmd"
  appendices:
    - "appendix-faq.qmd"
    - "common-problems.qmd"
    - "keyboard-shortcuts.qmd"
bibliography:
  - book.bib
  - packages.bib

format:
  html:
    theme:
      - cosmo
      - rpkgess.scss
    code-background: true
    code-copy: true
    code-overflow: wrap
    toc: true
  pdf:
    documentclass: krantz
    keep-tex: true
    cite-method: natbib
execute:
  freeze: false
  # epub:
  #   cover-image: cover.png

